### PR TITLE
Ms. Pacman Twin

### PR DESCRIPTION
**Pull request by arcadez2003**
* Added support for rare, Ms. Pacman Twin (mspactwin) simultaneous 2 player play [arcadez, grant2258, mahoneyt944]

### CODE REVIEW

**Comment by arcadez2003** [comment]
@amadvance i was clearing out some dev code i had kicking around and stumbled upon a part converted driver i
must have been working on some time back which adds support for Ms. Pacman Twin a recently dumped hack
which turns the game into a simultaneous two player version.

So i finished off the driver and here it is updated for this core im not 100% sure this will work i have some concerns
around the memory mapping but rather than rabbiting on about it now try the game and lemmie know if it works
and if not we can cross that bridge when it comes.

Regards.

**Comment by amadvance** [comment]
Hi @arcadez2003 
It looks like that we miss the definition of memory_set_opcode_base() in  MACHINE_RESET( mspactwin ). At present, it doesn't build, even adding all the following pull requests.
Can you please check?

**Comment by arcadez2003** [comment]
@amadvance damn i forgot that MAME totally changed the CPU decryption handling in the 101.u3 release, so long
story short the decryption code will need to be updated to work within your MAME106 codebase and it's not my
area of expertise unfortunately.

But i've asked @grant2258 who originally reworked the Ms Pacman Twin decryption for use in MAME78/84 if he 
could help us with this so hang tight for now.

**Comment by amadvance** [comment]
Thanks @grant2258, and don't worry. Take your time.

**Pull request merged**
