### PR TITLE
New Working Game Wing Force

### PR DESCRIPTION
**Pull request by arcadez2003**
0.170: ShouTime added 'Wing Force (Japan, prototype)' (Atlus 1993). Wing Force sound fixes and change VSync [trap15]: Sound was clearly incorrect before, now it sounds much closer to PCB video. Also changed the VSync rate to 59.1854 like Fujiyama Buster and B.Rap Boys, as it makes the title theme exit at the same point as the PCB video.

### CODE REVIEW

**Comment by arcadez2003** [comment]
@amadvance ignore the errors im confident all will be well when merged.

**Comment by amadvance** [comment]
Hi @arcadez2003 
Merged all, and the game play, but there is no sound at all...

**Comment by arcadez2003** [comment]
Alright @amadvance thanks for letting me know i'll look into it

**Comment by arcadez2003** [comment]
@amadvance hopefully this will sort it....
https://github.com/amadvance/advancemame/pull/143

**Comment by arcadez2003** [comment]
@amadvance On a seperate note your CPS2 driver doesn't support the last game released on that system namely
Hyper Street Fighter II it would be easy enough to add it here so the only question that remains is do you want me to.??

But before you answer i have to explain something........

MAME106 handles the encryption these games use via the ole XOR'S method that's to say these were released as data
files included in the romsets, Later MAME changed this cps decryption style and as a result instead of XOR's the roms now contain individual keys.

So since Hyper Street Fighter II was added to MAME after the above changes we cant support it without rewriting the
CPS decryption and then shifting all the roms over to use the new code and well that would be a ton of work for just
one game.!!!

However there is a workaround.........

Someone wanted to play this using the ole emulators so they created and released XOR's for the Asia set so it's 
possible to support that version here we simply get rid of the key loading and replace it with those XOR's and 
bingo it'll work using MAME106 as it does on my Xbox MAME cores.

As always there is a downside and this is why im hesitant to add it before running it by ya first.........

The problem is really obtaining a working rom as those user created XOR's are not part of any official MAME or FBN 
cores which means the standard roms available from the usual sites are not gonna contain the aformentioned XOR's
which were only available from some sites connected to CPS2 PCB hacking, these are long gone however im sure they
might be out there somewhere and users prepared for a scavenger hunt may well find em :)

So in closing users would need to have romsets for both hsf.zip and hsf2a.zip merge them making hsf2a the parent rom
and then add the XOR's, i have a fully compatable rom i can send your way for testing should you wanna add this
but your average user may stuggle to put all the parts together hence why im asking if you think it's worth support
Hyper SF II.

**Comment by amadvance** [comment]
@arcadez2003 
Good! Yes, please do it. I don't see a problem for the rom. I can make a new torrent with the new full rom set and put it somewhere.

**Comment by arcadez2003** [comment]
@amadvance added support for hsf2 as you requested, this is for testing purposes delete when you have it thx.
[hsf2.zip](https://github.com/user-attachments/files/16099698/hsf2.zip)

**Pull request merged**
