### PR TITLE
aquario

### PR DESCRIPTION
**Pull request by arcadez2003**

### CODE REVIEW

**Comment by arcadez2003** [comment]
@amadvance just a silly wee error as im pushing the commits one at a time this will merge fine.

**Comment by amadvance** [comment]
Hi @arcadez2003 
Can you send to me such rom? I cannot find anywhere...

**Comment by arcadez2003** [comment]
[For Testing.zip](https://github.com/amadvance/advancemame/files/14178764/For.Testing.zip)

**Comment by amadvance** [comment]
Thanks!

**Pull request merged**
