### PR TITLE
Small protection improvements for Sunset Riders

### PR DESCRIPTION
**Pull request by arcadez2003**
0.178: Fixed protection chip to use the work RAM buffer for horizontal scrolling in collision detection routine. Fixed players/enemies collision detection on slopes and characters judder when walking diagonally [Angelo Salese].

### CODE REVIEW

**Comment by arcadez2003** [comment]
@amadvance on reflection it might be better to just send you my latest source for advanceMAME, rather than clog up
the PR section with so many pull requests, i've left just three active a fix for DJ Boy compile problems and a couple more
with improvements emulation wise for Night Slashers and Sunset Riders.

Here is the source with a full changelog provided............
[amadvance.zip](https://github.com/amadvance/advancemame/files/4984409/amadvance.zip)

Feel free to use my code changes if you so desire if not then no hard feelings

Regards!!

**Comment by amadvance** [comment]
Hi @arcadez2003 

I've included your changes from advance.zip. Let me know if everything is right! 

Thanks!

**Comment by arcadez2003** [comment]
Hello @amadvance yes everything looks spot on, i hate to be a pest but TBH i dont have the tools to compile this core
if you could send me a build compatible with Windows i'll certainly do an indepth test of all the code changes.

Regards!!

**Comment by arcadez2003** [comment]
Hi @amadvance 

Here is the last of the code i have for ya, i've added the sound MCU for Ghox fixed a random crash issue which
affected Gunbird II and finally added support for Hyper Street Fighter II : The Anniversary Edition to the CPS2 driver

I've left brief notes around hsf2 in the txt file and updated the history.d document to reflect all the recent changes

[amadvance.zip](https://github.com/amadvance/advancemame/files/5009021/amadvance.zip)

Regards.

**Pull request closed without merging**
